### ISSUE TITLE
Support latest muRISCV-NN

### ISSUE THREAD

**Issue by PhilippvK** [tum-ei-eda/mlonmcu#18]
The new version of the library is going to be released soon, so we also want to use it in MLonMCU.

The integration process can be summarized as follows:

- [x] Implement MLonMCU Feature
- [x] Install dependencies via `mlonmcu setup`
- [x] Integrate into MLIF
- [x] Support TFLMI backend (should work out of the box with MLIF patches)
- [ ] Support TFLMC backend (needs patches, generation on host architecture feasible?)
- [x] Support and Test V-Extension
- [x] _Optional:_ Integration into TVM backends via CMSISNN BYOC wrappers

**Comment by fabianpedd** [comment]
Currently, some things in MURISCV-NN might be broken. Sorry about that. Will fix that soon. Should we maybe consider always using a compatible version of MURISCV-NN and TFLM by referring to certain commits? This way changes to upstream MURISCV-NN or TFLM won't break anything.

**Comment by fabianpedd** [comment]
We should also agree on an esp-idf version to use. They love to introduce breaking changes between major (and sometimes minor, arrgghh) versions (somewhat offtopic, but still relevant I guess).

**Comment by PhilippvK** [comment]
Good ideas, thats why the environment configuration is very useful. I would definitely pin most of those repos to a version which is known to work. However I am typically working using the `dev.yml.j2` template which might still point to the latest versions to make developing new features more easy.
