### ISSUE TITLE
Make model info optional for TVM backends

### ISSUE THREAD

**Issue by PhilippvK** [tum-ei-eda/mlonmcu#70]
We currently need to load our TFLite/TF models before invoking the TVMC command line to populate the `--input-shapes` argument, which is optional for most model types. Let's loosen up the requirement for model infos here which should make it easier to support more model formats in the future.

Just as a note: The refactored `validate` feature (using `.npz` files instead of raw `.bin` files) will eventually need the model info anyway to map model input names to input indices.

**Comment by PhilippvK** [comment]
This can not be implemented as easy as I thought, because the tvm wrapper generation currently depends on this. Let's hope that at some time TVM can generate those details (input shapes etc.) for us (There seems to already be work in that direction)

**Comment by rafzi** [comment]
Great, sounds like a good solution!
